-- Leads & Universities schema for CRM (idempotent)
begin;

-- 1) Universities catalog
create table if not exists public.universities (
  id          bigint generated by default as identity primary key,
  name        text not null,
  country     text,
  ranking     int,
  notes       text,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create index if not exists idx_universities_name on public.universities (lower(name));

alter table public.universities enable row level security;
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname='public' AND tablename='universities' AND policyname='universities_auth'
  ) THEN
    CREATE POLICY universities_auth ON public.universities
      FOR ALL TO authenticated
      USING (auth.uid() IS NOT NULL)
      WITH CHECK (auth.uid() IS NOT NULL);
  END IF;
END $$;

-- 2) Leads core table
create table if not exists public.leads (
  id                 bigint generated by default as identity primary key,
  first_name         text,
  last_name          text,
  email              text,
  phone              text,
  source             text check (source in ('facebook','instagram','google_form','walk_in','referral','organic')),
  status             text not null default 'new' check (status in ('new','documentation','university','visa','enrolled','rejected')),
  assigned_to_email  text,
  university_id      bigint references public.universities(id) on delete set null,
  tags               text[],
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now()
);

-- Ensure assigned_to_email exists even if leads table was created previously without it
alter table public.leads add column if not exists assigned_to_email text;


create index if not exists idx_leads_status on public.leads(status);
create index if not exists idx_leads_assigned_to on public.leads(assigned_to_email);
create index if not exists idx_leads_email_phone on public.leads(lower(email), phone);

alter table public.leads enable row level security;
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname='public' AND tablename='leads' AND policyname='leads_auth'
  ) THEN
    CREATE POLICY leads_auth ON public.leads
      FOR ALL TO authenticated
      USING (auth.uid() IS NOT NULL)
      WITH CHECK (auth.uid() IS NOT NULL);
  END IF;
END $$;

-- 3) Lead documents
create table if not exists public.lead_documents (
  id                bigint generated by default as identity primary key,
  lead_id           bigint not null references public.leads(id) on delete cascade,
  doc_type          text not null,
  file_url          text not null,
  uploaded_by_email text,
  created_at        timestamptz not null default now()
);

create index if not exists idx_lead_documents_lead on public.lead_documents(lead_id);

alter table public.lead_documents enable row level security;
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname='public' AND tablename='lead_documents' AND policyname='lead_docs_auth'
  ) THEN
    CREATE POLICY lead_docs_auth ON public.lead_documents
      FOR ALL TO authenticated
      USING (auth.uid() IS NOT NULL)
      WITH CHECK (auth.uid() IS NOT NULL);
  END IF;
END $$;

-- 4) Lead timeline
create table if not exists public.lead_timeline (
  id                bigint generated by default as identity primary key,
  lead_id           bigint not null references public.leads(id) on delete cascade,
  action            text not null,
  detail            text,
  created_by_email  text,
  created_at        timestamptz not null default now()
);

create index if not exists idx_lead_timeline_lead on public.lead_timeline(lead_id);

alter table public.lead_timeline enable row level security;
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname='public' AND tablename='lead_timeline' AND policyname='lead_timeline_auth'
  ) THEN
    CREATE POLICY lead_timeline_auth ON public.lead_timeline
      FOR ALL TO authenticated
      USING (auth.uid() IS NOT NULL)
      WITH CHECK (auth.uid() IS NOT NULL);
  END IF;
END $$;

commit;

