-- Explicit teacher-to-student assignments mapping
begin;

create table if not exists public.dashboard_teacher_student (
  id bigint generated by default as identity primary key,
  teacher_id text not null references public.dashboard_teachers(id) on delete cascade,
  student_id text not null references public.dashboard_students(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique(teacher_id, student_id)
);

create index if not exists idx_dts_teacher on public.dashboard_teacher_student (teacher_id);
create index if not exists idx_dts_student on public.dashboard_teacher_student (student_id);

commit;

