-- Add lead remarks history table and created_date column
-- This migration enables proper tracking of remarks with timestamps and user information

BEGIN;

-- 1) Create lead_remarks table for tracking remarks history
CREATE TABLE IF NOT EXISTS public.lead_remarks (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_id bigint NOT NULL REFERENCES public.leads(id) ON DELETE CASCADE,
  remark text NOT NULL,
  created_by_email text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_lead_remarks_lead_id ON public.lead_remarks(lead_id);
CREATE INDEX IF NOT EXISTS idx_lead_remarks_created_at ON public.lead_remarks(created_at DESC);

-- Enable RLS
ALTER TABLE public.lead_remarks ENABLE ROW LEVEL SECURITY;

-- Allow authenticated users to read and write remarks
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname='public' AND tablename='lead_remarks' AND policyname='lead_remarks_auth'
  ) THEN
    CREATE POLICY lead_remarks_auth ON public.lead_remarks
      FOR ALL TO authenticated
      USING (auth.uid() IS NOT NULL)
      WITH CHECK (auth.uid() IS NOT NULL);
  END IF;
END $$;

-- 2) Add created_date column to leads table (lead_date already exists, so we'll use that)
-- The lead_date column already exists from previous migration, so we just need to ensure it's populated
UPDATE public.leads 
SET lead_date = created_at::date 
WHERE lead_date IS NULL;

COMMIT;
